### ISSUE TITLE
[Suggestion] Some possible Config Options?

### ISSUE THREAD

**Issue by SonicX8000** [FatherToast/NaturalAbsorption#5]
Didn't know that you have a github for this mod. I apologize for the double comment but I feel that with it being in the github it wouldn't be forgotten in the comments on curseforge.

Anyway if by any chance you update, I wonder if these these suggestions could be considered... this is for 1.12.2 & up if you're planning on updating to newer versions of Minecraft.

1. Config option for the letting the Bonus Absorption Recovery based on Toughness work without setting the armor replacement to true.

2. Config Option for setting the maximum cap for Toughness for the Bonus Absorption Recovery. By default it caps out at 20 meaning that any extra Toughness at that point won't add any extra Bonus Recovery. Modded armors can go beyond 20 Toughness and the only bonus absorb I get is as if I only had 20 Toughness despite having 64 Toughness.

-----

Now this suggestion is a maybe considering that it may cause conflicts if certain mods check if you have absorb & such... but a config list to add in Damage Sources that Absorption won't block, meaning that absorb is ignored and instead affects health directly.
An example is if I list 'drown', 'arrow' in the list... those damage sources will act as if you had 0 absorb and will directly damage your health if you are drowning or getting hit by projectiles.

Another example is if I list 'mob', 'player', cactus'... mobs that melee you... or players that melee you... or touching any cacti or something that deals the cactus source will damage your health directly as if you had 0 Absorb.

P.S.
Is there a way to add in Extra Absorption via Quality Tools? Or does the author of that mod have to do that?

**Comment by FatherToast** [comment]
Hm, I see this comment is actually pretty old, but I'll do what I can:

1. The reworked configs allow this.  I think this came in 1.16.5.
2. There has never been any cap on this effect from NA; those are just the attributes' caps. Mod armors can't exceed them either without editing the vanilla attributes (and if they did, NA will work as expected for armor/toughness over 20).

As for the non-numbered things:
Making damage bypass absorption would be cool and is something I will continue to keep an eye out for, but it's not currently feasible.
I have no idea on Quality Tools, as I am not familiar with it. I have no plans to do that at this time, but it's not out of the question (assuming it's possible).
